name: TEST

on:
    push
  
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Running code
      run: |

        # python Test.py
        echo "Hola"

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Descargado archivos"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: hectorflores329@gmail.com
        commit_author: DataIntelligence BOT <hectorflores329@gmail.com>
        push_options: '--force'
